/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tsp.simulatie;

import javax.swing.JTextArea;

/**
 *
 * @author Johan
 */
public class LogScherm extends javax.swing.JInternalFrame {
    Logboek l;
    /**
     * Creates new form LogScherm
     */
    public LogScherm(Logboek l) {
        this.l = l;
        initComponents();
        makeLog();
    }

    private void makeLog()
    {
        for(int i = 0; i < l.getRecords().size(); i++)
        {
            getContentPane().add(new JTextArea("kaas"));
            getContentPane().add(new JTextArea("kaas"));
            getContentPane().add(new JTextArea("kaas"));
            getContentPane().add(new JTextArea("kaas"));
            getContentPane().add(new JTextArea("kaas"));
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane = new javax.swing.JScrollPane();

        setResizable(true);
        setMaximumSize(new java.awt.Dimension(480, 720));
        setMinimumSize(new java.awt.Dimension(480, 720));
        setPreferredSize(new java.awt.Dimension(480, 720));
        setVerifyInputWhenFocusTarget(false);
        getContentPane().setLayout(new java.awt.GridLayout(l.getRecords().size(), 5, 3, 5));

        jScrollPane.setOpaque(false);
        getContentPane().add(jScrollPane);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane;
    // End of variables declaration//GEN-END:variables
}
