package tsp.simulatie;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Johan
 */
public class TspScherm extends javax.swing.JFrame {

    int rows = 20;
    int cols = 20;
    private Vak[][] alleVakken;
    public String vakstring = "vakken:";

    /**
     * Creates new form TspScherm
     */
    public String vakje() {
        for (int row = 0; row < rows; row++) {
            for (int col = 0; col < cols; col++) {
                if (alleVakken[row][col].getIsGeselecteerd()) {
                    vakstring += alleVakken[row][col];
                }
            }
        }
        return vakstring;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton6 = new javax.swing.JToggleButton();
        int rows = 20;
        int cols = 20;
        int Lineborder = 1;
        int cellWidth = 720/(cols+(Lineborder*2));

        grid = new Grid(rows, cols, cellWidth, Lineborder);
        jPanelSelecties = grid;
        jPanel2 = new javax.swing.JPanel();
        jComboBoxSelectAlgoritme = new javax.swing.JComboBox();
        jLabelActies = new javax.swing.JLabel();
        jLabeltext1 = new javax.swing.JLabel();
        jLabelSelectedAlgoritme = new javax.swing.JLabel();
        jLabelAlgoritmeKiezen = new javax.swing.JLabel();
        jButtonStartSimulatie = new javax.swing.JButton();
        jButtonLogboekTonen = new javax.swing.JButton();
        jLabelLaatsteStatistieken = new javax.swing.JLabel();
        jTextFieldSelectedVakken = new javax.swing.JTextField();
        jButtonWisSelectie = new javax.swing.JButton();
        jLabelGeselecteerdeVakken = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableStats = new javax.swing.JTable();

        jToggleButton6.setText("jToggleButton6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 240, 240));
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(480, 360));
        setPreferredSize(new java.awt.Dimension(1600, 800));
        setResizable(false);

        jPanelSelecties.setBackground(new java.awt.Color(240, 0, 0));
        jPanelSelecties.setForeground(new java.awt.Color(255, 0, 0));
        jPanelSelecties.setMaximumSize(new java.awt.Dimension(720, 720));
        jPanelSelecties.setMinimumSize(new java.awt.Dimension(720, 720));
        jPanelSelecties.setPreferredSize(new java.awt.Dimension(720, 720));
        jPanelSelecties.setVerifyInputWhenFocusTarget(false);

        jPanel2.setBackground(new java.awt.Color(0, 240, 0));
        jPanel2.setForeground(new java.awt.Color(0, 0, 255));
        jPanel2.setAutoscrolls(true);
        jPanel2.setMaximumSize(new java.awt.Dimension(560, 720));
        jPanel2.setMinimumSize(new java.awt.Dimension(560, 720));
        jPanel2.setPreferredSize(new java.awt.Dimension(560, 720));

        jComboBoxSelectAlgoritme.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Volledige Enumeratie", "Nearest Neighbour", "Greedy Heuristic", " " }));
        jComboBoxSelectAlgoritme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSelectAlgoritmeActionPerformed(evt);
            }
        });

        jLabelActies.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelActies.setText("Acties");

        jLabeltext1.setText("Geselecteerde algoritme:");

        jLabelSelectedAlgoritme.setText("[algoritme]");

        jLabelAlgoritmeKiezen.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelAlgoritmeKiezen.setText("Algoritme kiezen");

        jButtonStartSimulatie.setText("Start simulatie");
        jButtonStartSimulatie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartSimulatieActionPerformed(evt);
            }
        });

        jButtonLogboekTonen.setText("Logboek tonen");

        jLabelLaatsteStatistieken.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelLaatsteStatistieken.setText("Laatste Statistieken");

        jTextFieldSelectedVakken.setText("vak, vak, vak, vak");
        jTextFieldSelectedVakken.setEnabled(false);

        jButtonWisSelectie.setText("Wis selectie");
        jButtonWisSelectie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWisSelectieActionPerformed(evt);
            }
        });

        jLabelGeselecteerdeVakken.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelGeselecteerdeVakken.setText("Geselecteerde vakken");

        jTableStats.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Afstand", "Algoritme", "Paketten", "Dimensies"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableStats.setEditingColumn(0);
        jTableStats.setEditingRow(0);
        jTableStats.setEnabled(false);
        jTableStats.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableStats);
        if (jTableStats.getColumnModel().getColumnCount() > 0) {
            jTableStats.getColumnModel().getColumn(0).setResizable(false);
            jTableStats.getColumnModel().getColumn(1).setResizable(false);
            jTableStats.getColumnModel().getColumn(2).setResizable(false);
            jTableStats.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonLogboekTonen)
                            .addComponent(jButtonStartSimulatie)
                            .addComponent(jLabelActies)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabeltext1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelSelectedAlgoritme))
                            .addComponent(jComboBoxSelectAlgoritme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAlgoritmeKiezen)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldSelectedVakken, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelGeselecteerdeVakken, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonWisSelectie))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelLaatsteStatistieken)))
                .addContainerGap(255, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAlgoritmeKiezen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxSelectAlgoritme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabeltext1)
                    .addComponent(jLabelSelectedAlgoritme))
                .addGap(73, 73, 73)
                .addComponent(jLabelActies)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonStartSimulatie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLogboekTonen)
                .addGap(59, 59, 59)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelGeselecteerdeVakken)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldSelectedVakken, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonWisSelectie))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                .addComponent(jLabelLaatsteStatistieken)
                .addGap(92, 92, 92)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanelSelecties, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelSelecties, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int comboBoxIndexSelected = 0;
    
    private void jComboBoxSelectAlgoritmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSelectAlgoritmeActionPerformed
        // TODO add your handling code here:
        System.out.println(jComboBoxSelectAlgoritme.getSelectedIndex());
        //volledige enum = 0
        //nearest neigbour = 1
        //greedy heurestic = 3
        
        comboBoxIndexSelected = jComboBoxSelectAlgoritme.getSelectedIndex();

    }//GEN-LAST:event_jComboBoxSelectAlgoritmeActionPerformed

    private void jButtonStartSimulatieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartSimulatieActionPerformed
        // TODO add your handling code here:
        Order order = new Order();
        Vak[][] vakken;
        
        vakken = grid.getAlleVakken();
        
        for (int row = 0; row < vakken.length; row++) {
            for (int col = 0; col < vakken[row].length; col++) {
                if(vakken[row][col].getIsGeselecteerd())
                {
                    order.addVak(vakken[row][col]);
                }
            }
        }
        
        if(comboBoxIndexSelected == 0)
        {
            Algoritme enumer = new Enumeratie(order);
        }else if(comboBoxIndexSelected == 1)
        {
            Algoritme nearest = new NearestNeighbor(order);
        }else if(comboBoxIndexSelected == 2)
        {
            Algoritme greedy = new GreedyHeuristic(order, rows);
        }else{
            System.out.println("something went horrible wrong");
        }

    }//GEN-LAST:event_jButtonStartSimulatieActionPerformed

    private void jButtonWisSelectieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWisSelectieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonWisSelectieActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TspScherm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TspScherm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TspScherm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TspScherm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TspScherm().setVisible(true);
            }
        });
    }

    private Grid grid;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogboekTonen;
    private javax.swing.JButton jButtonStartSimulatie;
    private javax.swing.JButton jButtonWisSelectie;
    private javax.swing.JComboBox jComboBoxSelectAlgoritme;
    private javax.swing.JLabel jLabelActies;
    private javax.swing.JLabel jLabelAlgoritmeKiezen;
    private javax.swing.JLabel jLabelGeselecteerdeVakken;
    private javax.swing.JLabel jLabelLaatsteStatistieken;
    private javax.swing.JLabel jLabelSelectedAlgoritme;
    private javax.swing.JLabel jLabeltext1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelSelecties;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableStats;
    private javax.swing.JTextField jTextFieldSelectedVakken;
    private javax.swing.JToggleButton jToggleButton6;
    // End of variables declaration//GEN-END:variables
}
