package tsp.simulatie;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Johan
 */
public class TspScherm extends javax.swing.JFrame {

    /**
     * Creates new form TspScherm
     */
    public TspScherm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton6 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton9 = new javax.swing.JToggleButton();
        jToggleButton10 = new javax.swing.JToggleButton();
        jToggleButton11 = new javax.swing.JToggleButton();
        jToggleButton12 = new javax.swing.JToggleButton();
        jToggleButton13 = new javax.swing.JToggleButton();
        jToggleButton14 = new javax.swing.JToggleButton();
        jToggleButton15 = new javax.swing.JToggleButton();
        jToggleButton16 = new javax.swing.JToggleButton();
        jToggleButton17 = new javax.swing.JToggleButton();
        jToggleButton18 = new javax.swing.JToggleButton();
        jToggleButton19 = new javax.swing.JToggleButton();
        jToggleButton20 = new javax.swing.JToggleButton();
        jToggleButton21 = new javax.swing.JToggleButton();
        jToggleButton22 = new javax.swing.JToggleButton();
        jToggleButton23 = new javax.swing.JToggleButton();
        jToggleButton24 = new javax.swing.JToggleButton();
        jToggleButton25 = new javax.swing.JToggleButton();
        jToggleButton26 = new javax.swing.JToggleButton();
        jToggleButton27 = new javax.swing.JToggleButton();
        jToggleButton28 = new javax.swing.JToggleButton();
        jToggleButton29 = new javax.swing.JToggleButton();
        jToggleButton30 = new javax.swing.JToggleButton();
        jToggleButton31 = new javax.swing.JToggleButton();
        jToggleButton32 = new javax.swing.JToggleButton();
        jToggleButton33 = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jComboBoxSelectAlgoritme = new javax.swing.JComboBox();
        jLabelActies = new javax.swing.JLabel();
        jLabeltext1 = new javax.swing.JLabel();
        jLabelSelectedAlgoritme = new javax.swing.JLabel();
        jLabelAlgoritmeKiezen = new javax.swing.JLabel();
        jButtonStartSimulatie = new javax.swing.JButton();
        jButtonLogboekTonen = new javax.swing.JButton();
        jLabelLaatsteStatistieken = new javax.swing.JLabel();
        jTextFieldSelectedVakken = new javax.swing.JTextField();
        jButtonWisSelectie = new javax.swing.JButton();
        jLabelGeselecteerdeVakken = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableStats = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabelCord6 = new javax.swing.JLabel();
        jLabelCord5 = new javax.swing.JLabel();
        jLabelCord4 = new javax.swing.JLabel();
        jLabelCord3 = new javax.swing.JLabel();
        jLabelCord2 = new javax.swing.JLabel();
        jLabelCord1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabelCordA = new javax.swing.JLabel();
        jLabelCordB = new javax.swing.JLabel();
        jLabelCord = new javax.swing.JLabel();
        jLabelCordD = new javax.swing.JLabel();
        jLabelCordE = new javax.swing.JLabel();

        jToggleButton6.setText("jToggleButton6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 240, 240));
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(240, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.setMaximumSize(new java.awt.Dimension(836, 696));
        jPanel1.setMinimumSize(new java.awt.Dimension(836, 696));
        jPanel1.setPreferredSize(new java.awt.Dimension(836, 696));
        jPanel1.setVerifyInputWhenFocusTarget(false);
        jPanel1.setLayout(new java.awt.GridLayout(6, 5, 6, 6));

        jToggleButton1.setText("jToggleButton1");
        jPanel1.add(jToggleButton1);

        jToggleButton2.setText("jToggleButton2");
        jPanel1.add(jToggleButton2);

        jToggleButton3.setText("jToggleButton3");
        jPanel1.add(jToggleButton3);

        jToggleButton4.setText("jToggleButton4");
        jPanel1.add(jToggleButton4);

        jToggleButton5.setText("jToggleButton5");
        jPanel1.add(jToggleButton5);

        jToggleButton9.setText("jToggleButton9");
        jPanel1.add(jToggleButton9);

        jToggleButton10.setText("jToggleButton10");
        jPanel1.add(jToggleButton10);

        jToggleButton11.setText("jToggleButton11");
        jPanel1.add(jToggleButton11);

        jToggleButton12.setText("jToggleButton12");
        jPanel1.add(jToggleButton12);

        jToggleButton13.setText("jToggleButton13");
        jPanel1.add(jToggleButton13);

        jToggleButton14.setText("jToggleButton14");
        jPanel1.add(jToggleButton14);

        jToggleButton15.setText("jToggleButton15");
        jPanel1.add(jToggleButton15);

        jToggleButton16.setText("jToggleButton16");
        jPanel1.add(jToggleButton16);

        jToggleButton17.setText("jToggleButton16");
        jPanel1.add(jToggleButton17);

        jToggleButton18.setText("jToggleButton16");
        jPanel1.add(jToggleButton18);

        jToggleButton19.setText("jToggleButton16");
        jPanel1.add(jToggleButton19);

        jToggleButton20.setText("jToggleButton16");
        jPanel1.add(jToggleButton20);

        jToggleButton21.setText("jToggleButton16");
        jPanel1.add(jToggleButton21);

        jToggleButton22.setText("jToggleButton16");
        jPanel1.add(jToggleButton22);

        jToggleButton23.setText("jToggleButton16");
        jPanel1.add(jToggleButton23);

        jToggleButton24.setText("jToggleButton16");
        jPanel1.add(jToggleButton24);

        jToggleButton25.setText("jToggleButton16");
        jPanel1.add(jToggleButton25);

        jToggleButton26.setText("jToggleButton16");
        jPanel1.add(jToggleButton26);

        jToggleButton27.setText("jToggleButton16");
        jPanel1.add(jToggleButton27);

        jToggleButton28.setText("jToggleButton16");
        jPanel1.add(jToggleButton28);

        jToggleButton29.setText("jToggleButton16");
        jPanel1.add(jToggleButton29);

        jToggleButton30.setText("jToggleButton16");
        jPanel1.add(jToggleButton30);

        jToggleButton31.setText("jToggleButton16");
        jPanel1.add(jToggleButton31);

        jToggleButton32.setText("jToggleButton16");
        jPanel1.add(jToggleButton32);

        jToggleButton33.setText("jToggleButton16");
        jPanel1.add(jToggleButton33);

        jPanel2.setBackground(new java.awt.Color(0, 240, 0));
        jPanel2.setForeground(new java.awt.Color(0, 0, 255));
        jPanel2.setAutoscrolls(true);
        jPanel2.setMaximumSize(new java.awt.Dimension(420, 720));
        jPanel2.setMinimumSize(new java.awt.Dimension(420, 720));
        jPanel2.setPreferredSize(new java.awt.Dimension(420, 720));

        jComboBoxSelectAlgoritme.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Volledige Enumeratie", "Nearest Neighbour", "Greedy Heuristic", " " }));
        jComboBoxSelectAlgoritme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSelectAlgoritmeActionPerformed(evt);
            }
        });

        jLabelActies.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelActies.setText("Acties");

        jLabeltext1.setText("Geselecteerde algoritme:");

        jLabelSelectedAlgoritme.setText("[algoritme]");

        jLabelAlgoritmeKiezen.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelAlgoritmeKiezen.setText("Algoritme kiezen");

        jButtonStartSimulatie.setText("Start simulatie");
        jButtonStartSimulatie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartSimulatieActionPerformed(evt);
            }
        });

        jButtonLogboekTonen.setText("Logboek tonen");

        jLabelLaatsteStatistieken.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelLaatsteStatistieken.setText("Laatste Statistieken");

        jTextFieldSelectedVakken.setText("vak, vak, vak, vak");
        jTextFieldSelectedVakken.setEnabled(false);

        jButtonWisSelectie.setText("Wis selectie");
        jButtonWisSelectie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWisSelectieActionPerformed(evt);
            }
        });

        jLabelGeselecteerdeVakken.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelGeselecteerdeVakken.setText("Geselecteerde vakken");

        jTableStats.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Afstand", "Algoritme", "Paketten", "Dimensies"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableStats.setEditingColumn(0);
        jTableStats.setEditingRow(0);
        jTableStats.setEnabled(false);
        jTableStats.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableStats);
        if (jTableStats.getColumnModel().getColumnCount() > 0) {
            jTableStats.getColumnModel().getColumn(0).setResizable(false);
            jTableStats.getColumnModel().getColumn(1).setResizable(false);
            jTableStats.getColumnModel().getColumn(2).setResizable(false);
            jTableStats.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonLogboekTonen)
                            .addComponent(jButtonStartSimulatie)
                            .addComponent(jLabelActies)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabeltext1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelSelectedAlgoritme))
                            .addComponent(jComboBoxSelectAlgoritme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAlgoritmeKiezen)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldSelectedVakken, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelGeselecteerdeVakken, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonWisSelectie))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelLaatsteStatistieken)))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAlgoritmeKiezen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxSelectAlgoritme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabeltext1)
                    .addComponent(jLabelSelectedAlgoritme))
                .addGap(73, 73, 73)
                .addComponent(jLabelActies)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonStartSimulatie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLogboekTonen)
                .addGap(59, 59, 59)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelGeselecteerdeVakken)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldSelectedVakken, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonWisSelectie))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelLaatsteStatistieken)
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        jPanel3.setBackground(new java.awt.Color(240, 0, 240));
        jPanel3.setMaximumSize(new java.awt.Dimension(24, 696));
        jPanel3.setMinimumSize(new java.awt.Dimension(24, 696));
        jPanel3.setPreferredSize(new java.awt.Dimension(24, 696));
        jPanel3.setLayout(new java.awt.GridLayout(6, 0, 0, 6));

        jLabelCord6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCord6.setText("6");
        jPanel3.add(jLabelCord6);

        jLabelCord5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCord5.setText("5");
        jPanel3.add(jLabelCord5);

        jLabelCord4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCord4.setText("4");
        jPanel3.add(jLabelCord4);

        jLabelCord3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCord3.setText("3");
        jPanel3.add(jLabelCord3);

        jLabelCord2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCord2.setText("2");
        jPanel3.add(jLabelCord2);

        jLabelCord1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCord1.setText("1");
        jPanel3.add(jLabelCord1);

        jPanel4.setBackground(new java.awt.Color(0, 240, 240));
        jPanel4.setMaximumSize(new java.awt.Dimension(836, 24));
        jPanel4.setMinimumSize(new java.awt.Dimension(836, 24));
        jPanel4.setPreferredSize(new java.awt.Dimension(836, 24));
        jPanel4.setLayout(new java.awt.GridLayout(1, 5, 6, 0));

        jLabelCordA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCordA.setText("A");
        jPanel4.add(jLabelCordA);

        jLabelCordB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCordB.setText("B");
        jPanel4.add(jLabelCordB);

        jLabelCord.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCord.setText("C");
        jPanel4.add(jLabelCord);

        jLabelCordD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCordD.setText("D");
        jPanel4.add(jLabelCordD);

        jLabelCordE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCordE.setText("E");
        jPanel4.add(jLabelCordE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxSelectAlgoritmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSelectAlgoritmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSelectAlgoritmeActionPerformed

    private void jButtonStartSimulatieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartSimulatieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonStartSimulatieActionPerformed

    private void jButtonWisSelectieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWisSelectieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonWisSelectieActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TspScherm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TspScherm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TspScherm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TspScherm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TspScherm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogboekTonen;
    private javax.swing.JButton jButtonStartSimulatie;
    private javax.swing.JButton jButtonWisSelectie;
    private javax.swing.JComboBox jComboBoxSelectAlgoritme;
    private javax.swing.JLabel jLabelActies;
    private javax.swing.JLabel jLabelAlgoritmeKiezen;
    private javax.swing.JLabel jLabelCord;
    private javax.swing.JLabel jLabelCord1;
    private javax.swing.JLabel jLabelCord2;
    private javax.swing.JLabel jLabelCord3;
    private javax.swing.JLabel jLabelCord4;
    private javax.swing.JLabel jLabelCord5;
    private javax.swing.JLabel jLabelCord6;
    private javax.swing.JLabel jLabelCordA;
    private javax.swing.JLabel jLabelCordB;
    private javax.swing.JLabel jLabelCordD;
    private javax.swing.JLabel jLabelCordE;
    private javax.swing.JLabel jLabelGeselecteerdeVakken;
    private javax.swing.JLabel jLabelLaatsteStatistieken;
    private javax.swing.JLabel jLabelSelectedAlgoritme;
    private javax.swing.JLabel jLabeltext1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableStats;
    private javax.swing.JTextField jTextFieldSelectedVakken;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton10;
    private javax.swing.JToggleButton jToggleButton11;
    private javax.swing.JToggleButton jToggleButton12;
    private javax.swing.JToggleButton jToggleButton13;
    private javax.swing.JToggleButton jToggleButton14;
    private javax.swing.JToggleButton jToggleButton15;
    private javax.swing.JToggleButton jToggleButton16;
    private javax.swing.JToggleButton jToggleButton17;
    private javax.swing.JToggleButton jToggleButton18;
    private javax.swing.JToggleButton jToggleButton19;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton20;
    private javax.swing.JToggleButton jToggleButton21;
    private javax.swing.JToggleButton jToggleButton22;
    private javax.swing.JToggleButton jToggleButton23;
    private javax.swing.JToggleButton jToggleButton24;
    private javax.swing.JToggleButton jToggleButton25;
    private javax.swing.JToggleButton jToggleButton26;
    private javax.swing.JToggleButton jToggleButton27;
    private javax.swing.JToggleButton jToggleButton28;
    private javax.swing.JToggleButton jToggleButton29;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton30;
    private javax.swing.JToggleButton jToggleButton31;
    private javax.swing.JToggleButton jToggleButton32;
    private javax.swing.JToggleButton jToggleButton33;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton9;
    // End of variables declaration//GEN-END:variables
}
